### ISSUE TITLE
Bootstrap estimates

### ISSUE THREAD

**Issue by steffejr** [QuentinAndre/pyprocessmacro#8]
I am doing a simple model of A --> B --> C.
When the get_bootstratp_estimates function is run, it returns the bootstrap estimates for the model of A and B predicting C. However, these estimates are not the ones needed to estimate the bootstrap estimates for the indirect effect. We would also need the estimates for the A to B model.

**Comment by QuentinAndre** [comment]
Hi Jason,

I am not sure I understand the issue. Could you tell me what is not working properly for you?

Best,

Quentin

**Comment by steffejr** [comment]
I was trying to plot a histogram of the bootstrap distributions for the indirect effect. It seemed to me that the parameters saved are the A and B predictors for the A+B = C model.

**Comment by QuentinAndre** [comment]
Hi Jason,

Let's assume for simplicity that you are running Model 4: X -> M -> Y.

```
p = Process(x="X", y="Y", m="M", data=df, model=4)
ests = p.get_bootstrap_estimates()
```

The variable `ests` then contains all the coefficients for _all_ models, not just for Y ~ X + M. 

If you examine the dataframe `ests` returned by `get_bootstrap_estimates()`, you will see that it contains a column called `OutcomeName`. This column identifies the model:

*  It is "M" if the model was M ~ X, 
* It is "Y" if the model was Y ~ X + M. 

If you subset the dataframe using this column, you will be able to recover the coefficients for each model.
```
# Coefficients when X is the outcome
coeffs_dv = ests[ests["OutcomeName"] == "Y"]

# Coefficients when M is the outcome.
coeffs_mediator = ests[ests["OutcomeName"] == "M"]
```

You will notice that the column `M` is `NaN` in `coeffs_mediator`, because `M` was (obviously) not a predictor in this model.

From there, if you want to plot the distribution of the indirect effect, all you have to do is:

```
x_on_m = coeffs_mediator["X"].values # Effect of X on M
m_on_y = coeffs_dv["M"].values # Effect of M on Y controlling for X
ind_effect = x_on_m*m_on_y
sns.distplot(ind_effect)
```

Hope it helps,

Quentin.

**Comment by steffejr** [comment]
Merci
