### ISSUE TITLE
Bug for model58,59

### ISSUE THREAD

**Issue by amrain-py** [QuentinAndre/pyprocessmacro#9]
Hey  QuentinAndre,
Thanks for your great work.
When I run this model58 "Process(data=df, model=58, x="x1", m=["m1"], w="m2",y="y")", the same as model59, and the results as following,
 "mod1, mod2 = self._moderators_symb  # Only two moderators
ValueError: not enough values to unpack (expected 2, got 1) ".
However, Only one "w" is enough for model58 and model 59. So some bugs here?

Great thanks once more.

**Comment by QuentinAndre** [comment]
I figured out the issue! I'm working on it, expect an update in the next few days.

**Comment by QuentinAndre** [comment]
This is fixed! You can now download the new version using `pip install pyprocessmacro==1.0.3`.
In models 58 and 59, the same moderator `W` is present on two different paths. Because of an error in the way my code was counting the number of distinct moderators, pyprocessmacro was therefore expecting two different moderators to be present in the model.

**Comment by amrain-py** [comment]
Hey Quentin ANDRE,

Many thanks for your great work.

Thanks.

 
From: Quentin ANDRE
Date: 2019-10-01 15:53
To: QuentinAndre/pyprocessmacro
CC: amrain-py; Author
Subject: Re: [QuentinAndre/pyprocessmacro] Bug for model58,59 (#9)
This is fixed! You can now download the new version using pip install pyprocessmacro==1.0.3.
In models 58 and 59, the same moderator W is present on two different paths. Because of an error in the way my code was counting the number of distinct moderators, pyprocessmacro was therefore expecting two different moderators to be present in the model.
